version: 2
jobs:
  build:
    working_directory: /go/src/github.com/abema/go-mp4
    docker:
    - image: circleci/golang:1.14
    steps:
    - checkout
    - run: go vet ./...
    - run: go test -coverprofile=coverage.txt -covermode=count ./...
    - run: bash <(curl -s https://codecov.io/bash)
