version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.17
    steps:
    - checkout
    - run: go test -coverprofile=coverage.txt -covermode=count ./...
    - run: go install github.com/mattn/goveralls@v0.0.8
    - run: goveralls -coverprofile=coverage.txt -service=circle-ci
