version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.14
    steps:
    - checkout
    - run: go vet ./...
    - run: go test -coverprofile=coverage.txt -covermode=count ./...
    - run: go install ./mp4tool
    - persist_to_workspace:
        root: .
        paths:
        - .
  coverage:
    docker:
    - image: circleci/golang:1.16
    steps:
    - attach_workspace:
        at: .
    - run: go install github.com/mattn/goveralls@v0.0.8
    - run: goveralls -coverprofile=coverage.txt -service=circle-ci
