name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        # FIXME: windows-latest not working
        # os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ ubuntu-latest, macos-latest ]
        go-version: [ "1.17", "1.18", ">=1.19" ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
    - run: go vet ./...
    - run: go test -coverprofile=coverage.txt -covermode=atomic ./...
    - run: go install ./mp4tool
    - name: Upload Coverage Report
      if: ${{ github.event_name == 'push' && matrix.os == 'ubuntu-latest' && matrix.go-version == '1.17' }}
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        go install github.com/mattn/goveralls@latest
        goveralls -coverprofile=coverage.txt
