name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go-version: [ "1.20", "1.21", ">=1.22" ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
    - run: go vet ./...
    - run: go test "-coverprofile=coverage.txt" -covermode=atomic ./...
    - run: go install ./cmd/mp4tool
    - name: Upload Coverage Report
      if: ${{ github.event_name == 'push' && matrix.os == 'ubuntu-latest' && matrix.go-version == '1.19' }}
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        go install github.com/mattn/goveralls@latest
        goveralls -coverprofile=coverage.txt
